### ISSUE TITLE
Business Scrub takes 99 rupees for Piece of Heart, doesn’t give me Piece of Heart

### ISSUE THREAD

**Issue by avidrissman** [Zelllll/tml#12] opened 2020-08-01 04:48 UTC
v1.3, on OpenEmu 2.2.1, Mupen64Plus core 2.5.9

In the tall tree stump in the Deku Grove lives a Business Scrub who promises to sell a Piece of Heart for 99 rupees. I give him 99 rupees, I get nothing.

This may well be intended behavior to get scammed by a Business Scrub but I found it surprising.

https://youtu.be/LROdFBQMf5o

**Comment by ethanccss** [comment] 2020-08-02 01:02
SPOILER ALERT>    Its a joke. If you read the books around the game, I think in the library, it literally says not to buy anything from them as they'll scam you. He gives you a "piece" of a heart, like 1/4 hearts for 99 rupees haha. I laughed after I fell for it.

**Comment by Zelllll** [comment] 2020-08-02 19:25
It's actually not a joke and yet another issue after this was supposed to have been fixed three times.. wait for 1.4.

**Comment by Zelllll** [comment] 2020-08-02 23:46
This is now fixed. The issue is actually technically related to your save file, so the scrub now works a little differently in order to prevent issues with saves from older releases of the game.

**Closed by Zelllll** 2020-08-02 23:46 UTC
